#!/bin/bash

# MEDWEG AWS Secrets Manager Setup Script
# This script creates all required secrets in AWS Secrets Manager

set -e

AWS_REGION=${AWS_REGION:-"eu-central-1"}

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  MEDWEG Secrets Setup${NC}"
echo -e "${GREEN}========================================${NC}"

# Function to create or update secret
create_secret() {
    local secret_name=$1
    local secret_value=$2

    # Try to create the secret
    aws secretsmanager create-secret \
        --name "${secret_name}" \
        --secret-string "${secret_value}" \
        --region ${AWS_REGION} 2>/dev/null || \
    # If it already exists, update it
    aws secretsmanager update-secret \
        --secret-id "${secret_name}" \
        --secret-string "${secret_value}" \
        --region ${AWS_REGION}

    echo -e "${GREEN}✓ Secret created/updated: ${secret_name}${NC}"
}

# Generate secure random keys
echo -e "\n${YELLOW}Generating secure keys...${NC}"
DB_ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")
JWT_REFRESH_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")

echo -e "${GREEN}Keys generated${NC}"

# Prompt for required values
echo -e "\n${YELLOW}Please provide the following values:${NC}"

read -p "Database Host (RDS endpoint): " DB_HOST
read -p "Database Name [MEDWEG]: " DB_NAME
DB_NAME=${DB_NAME:-MEDWEG}

read -p "Database User [postgres]: " DB_USER
DB_USER=${DB_USER:-postgres}

read -sp "Database Password: " DB_PASSWORD
echo

read -p "AWS Access Key ID (for S3/SES): " AWS_ACCESS_KEY
read -sp "AWS Secret Access Key: " AWS_SECRET_KEY
echo

echo -e "\n${YELLOW}Generating VAPID keys for push notifications...${NC}"
# Generate VAPID keys
VAPID_OUTPUT=$(npx web-push generate-vapid-keys --json 2>/dev/null)
VAPID_PUBLIC_KEY=$(echo $VAPID_OUTPUT | node -e "console.log(JSON.parse(require('fs').readFileSync(0)).publicKey)")
VAPID_PRIVATE_KEY=$(echo $VAPID_OUTPUT | node -e "console.log(JSON.parse(require('fs').readFileSync(0)).privateKey)")

read -p "Email User (Gmail): " EMAIL_USER
read -sp "Email Password (App Password): " EMAIL_PASSWORD
echo

read -p "Email From Address [${EMAIL_USER}]: " EMAIL_FROM
EMAIL_FROM=${EMAIL_FROM:-${EMAIL_USER}}

# Create secrets
echo -e "\n${YELLOW}Creating secrets in AWS Secrets Manager...${NC}"

create_secret "medweg/db-host" "${DB_HOST}"
create_secret "medweg/db-name" "${DB_NAME}"
create_secret "medweg/db-user" "${DB_USER}"
create_secret "medweg/db-password" "${DB_PASSWORD}"
create_secret "medweg/db-encryption-key" "${DB_ENCRYPTION_KEY}"
create_secret "medweg/jwt-secret" "${JWT_SECRET}"
create_secret "medweg/jwt-refresh-secret" "${JWT_REFRESH_SECRET}"
create_secret "medweg/aws-access-key-id" "${AWS_ACCESS_KEY}"
create_secret "medweg/aws-secret-key" "${AWS_SECRET_KEY}"
create_secret "medweg/vapid-public-key" "${VAPID_PUBLIC_KEY}"
create_secret "medweg/vapid-private-key" "${VAPID_PRIVATE_KEY}"
create_secret "medweg/email-user" "${EMAIL_USER}"
create_secret "medweg/email-password" "${EMAIL_PASSWORD}"

# Save configuration for local use
echo -e "\n${YELLOW}Saving configuration for local use...${NC}"

cat > .env.production <<EOF
# Generated by setup-secrets.sh - $(date)
# DO NOT COMMIT THIS FILE

# Server Configuration
NODE_ENV=production
PORT=5000
API_VERSION=v1

# Database Configuration
DB_HOST=${DB_HOST}
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_SSL=true
DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY}

# JWT Secrets
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d

# AWS Configuration
AWS_REGION=${AWS_REGION}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
S3_BUCKET_NAME=medweg-invoices
SES_SENDER_EMAIL=noreply@medweg.de

# PWA Push Notifications
VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
VAPID_SUBJECT=mailto:admin@medweg.de

# URLs (Update with your ALB DNS)
FRONTEND_URL=http://YOUR_ALB_DNS
BACKEND_URL=http://YOUR_ALB_DNS

# Email Configuration
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_SECURE=false
EMAIL_USER=${EMAIL_USER}
EMAIL_PASSWORD=${EMAIL_PASSWORD}
EMAIL_FROM_NAME=MEDWEG Bavaria
EMAIL_FROM_ADDRESS=${EMAIL_FROM}

# Other
EMAIL_VERIFICATION_CODE_EXPIRY_MINUTES=10
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
RATE_LIMIT_LOGIN_MAX=5
LOG_LEVEL=info
LOG_FILE_PATH=./logs
CRON_ENABLED=true
CRON_TIMEZONE=Europe/Berlin
EOF

# Frontend environment
cat > frontend/.env.production <<EOF
# Frontend Production Environment
VITE_API_URL=http://YOUR_ALB_DNS/api/v1
VITE_API_TIMEOUT=10000
VITE_VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VITE_APP_NAME=MEDWEG
VITE_APP_VERSION=0.1.0
VITE_NODE_ENV=production
EOF

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}  Secrets Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "\n${YELLOW}Important:${NC}"
echo -e "1. .env.production file created (DO NOT COMMIT)"
echo -e "2. Update FRONTEND_URL and BACKEND_URL with your ALB DNS"
echo -e "3. Update frontend/.env.production with your ALB DNS"
echo -e "4. All secrets are stored in AWS Secrets Manager"
echo -e "\n${GREEN}VAPID Public Key (save for frontend):${NC}"
echo -e "${VAPID_PUBLIC_KEY}"
